# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

	KnowledgeArea.create([{name: 'Informatica'},{name: 'Otros'},{name: 'Liderazgo'},{name: 'Trabajo en equipo'}])


	v={"Abogado"=>[],
		"Administracion"=>["Escolar","Internacional", "Publica","y Direccion de Empresas","de Empresas"],
		"Agronomia"=>[],
		"Arquitecto"=>[],
	 "Artesano"=>[],
	 "Auditor"=>[],
	 "Auxiliar"=>["Contabilidad","de Oficina"],
	 "Ayudante de Gerencia"=>[],
	 "Bachiller"=>["En Humanidades"],
	 "Bachillerato Internacional"=>[],
	 "Bibliotecologo"=>[],
	 "Biologo"=>[],
	 "Bioquimico"=>[]
 }
 schools_total=["GESTIÓN PÚBLICA Y EMPRESARIAL","DIRECCIÓN GENERAL DE BIODIVERSIDAD Y ÁREAS PROTEGIDAS","MINISTERIO DE MEDIO AMBIENTE Y AGUA (MMAYA)","UNIVERSIDAD NUESTRA SEÑORA DE LA PAZ","UNIVERSIDAD DE SARAJEVO",
	 							"PRAGMAGIA","MINISTERIO DE EDUCACIÓN - BOLIVIA","UNIVERSIDAD MILITAR MCAL. BERNARDINO BILBAO R.","ESCUELA NORMAL SUP. SIMON BOLIVAR","INFORMATICA WIÑAY PACHA","UNI","UNIVERSIDAD MILITAR DE LAS FFAA. DE LA NACION",
								"ABRAHAM LINCOLN INSTITUTE","UNIVERSIDAD PÚBLICA DE EL ALTO","UNIVERSIDAD MILITAR DE LAS FF.AA. DE LA NACION","NORMAL INTEGRADA 'SIMÓN BOLIVAR'  LA PAZ","U.A.S.P. - LA PAZ","MINISTERIO DE EDUCACIÓN - AECI",
								"INSTITUTO EDUCACIONAL 'BRITÁNICO'","INST. NAL. DE FORMACIÓN ALTERNATIVA","CENTRO EDUCATIVO TÉCNICO 'MRCAL. SUCRE'","MINISTERIO DE EDUCACIÓN DE BOLIVIA","UNFPA - UNESCO","COMISIÓN EPISCOPAL DE EDUCACIÓN",
								"SOUTH AMERICAN SCHOOLS","UNIVERSIDAD PRIVADA CATÓLICA 'LA SALLE'","EMBAJADA DE ESPAÑA","PIEB","PROCEP - AIPE","PNUD - UNESCO","UNIVERSIDAD ANDINA SIMÓN BOLIVAR","UNIVERSIDAD CATOLICA DE SANTIAGO DEL EST",
								"PONTIFICIA UNIVERSIDAD DE RIO DE JANEIRO","UCB UNIDAD LA PAZ","UNIVERSIDAD EVANGELICA BOLIVIANA","UNIVERSIDAD TECNOLOGICA BOLIVIANA - UTB","UNIVERSIDAD FRANZ TAMAYO","AMERICAN UNIVERSITY","UNIVERSIDAD SANTO TOMAS DE AQUINO",
								"UNIVERSIDAD PRIVADA BOLIVIANA - U.P.B.","UNIVERSIDAD IBEROAMERICANA","UNIVERSIDAD MAYOR DE SAN ANDRES - UMSA","ESCUELA MILITAR DE INGENIERIA - E.M.I. L","ESCUELA MILITAR DE INGENIERIA EMI - ANTONIO JOSE DE SUCRE",
								"UNIVERSIDAD MAYOR SAN FRANCISCO XAVIER","UNIVERSIDAD SAN FRANCISCO XAVIER","SANSUNG IP INSTITUTE","UNIVERSIDAD PRIVADA DOMINGO SAVIO","DGQ","ESCUELA MILITAR DE INGENIERIA - E.M.I. C","FE Y ALEGRIA","KHANA MARKA",
								"ATENEO PONTIFICIO REGINA APOSTOLORUM","INSTITUTO JESÚS MARÍA","ASOCIACION MUNDIAL DE PSICOANÁLISIS","INSTITUTO PARA EL DESARROLLO HUMANO","CENTRO DE FORMACIÓN Y CAPACITACIÓN PERMANENTE VISIÓN 3000","CENTRO DE ESTUDIOS GABRIEL REINOSO",
								"ASOCIACIÓN BOLIVIANA DE EDUCACIÓN CATÓLICA - ABEC","SEDEGES","CENTRO DE INVESTIGACIÓN Y CAPACITACIÓN EN SABERES ALTERNATIVOS","FEDERACIÓN DE ASOCIACIONES MUNICIPALES DE BOLIVIA - FAM","INSTITUTO BOLIVIANO  DE TEOLOGÍA A DISTANCIA - CATÓLICA","AMERICAN INTERNATIONAL SCHOOL OF BOLIVIA - AISB",
								"ASOCIACIÓN DE HOGARES, CENTROS, ASILOS - ASHONA","COLEGIO DE PSICÓLOGOS COCHABAMBA - CPC","GRECO","SEMINARIO CONCILIAR SAN CRISTOBAL","INST. INTERCONGR. DE LA CONF. DE RELIG","CAMARA DPTAL. DE INDUSTRIA CBBA.","IBNORCA","INST. NORMAL SUPERIOR CATOLICO","SEMLA","INTER NAZARETH","MARIANUM PONTIFICIA FACOLTA TEOLOGICA",
								"INST. DE FIL. Y HUMANIDADES LUIS ESPINAL","FUND. CIENTIFICA BOLIVIANA Y COLUMBUS","SEMINARIO MAYOR SAN JERONIMO","INSTITUTO TÉCNICO INTEGRAL 'EMMA'","INSTITUTO DE EDUCACIÓN BANCARIA DE CBBA.","INSTITUTO TÉCNICO HUMANÍSTICO","DIRECCIÓN GENERAL DE IMPUESTOS INTERNOS","CENTRO DE FOMENTO A INICIATIVAS ECONÓMIC","INSTITUTO I.C.E.P.",
								"COMPLEJO EDUCATIVO ADVENTISTA DE BOLIVIA","INSTITUTO COMPUTACIONAL ASC II","ATLÁNDIDA CONSULTORES","INSTITUTO DE EDUCACIÓN TÉCNICA 'IDET'","TECNOLÓGICO ANDRÉS BELLO","BOLIVIANA DE INFORMÁTICA Y TECNOLOGÍA CB","SEMINARIO FRANCISCANO","TECNOLÓGICO INDUSTRIAL BOL-CAN 'EL PASO'","C.E.S.U. - CBBA.",
								"MASTER CCCN - BOLIVIA","ABSE (ASOC. BOL. SECRETARIAS)","PIEB - REPOC","INSTITUTO CANADIENSE","INSTITUTO AMERICANO DE COMPUTACIÓN","INCOS II","IDEA","SEMINARIO SAN LUIS","ESCUELA DE COMANDO Y ESTADO MAYOR ECEM","MASTER CCCN","TECNOLOGICO DEL VALLE","UNESCO - UMSS - CELAT","INSTITUTO PSIQUIÁTRICO 'SAN JUAN DE DIOS'",
								"CENACO CEIN","UNIVERSIDAD ADVENTISTA DE BOLIVIA","INSTITUTO  FORMACIÓN Y CAPACITACIÓN LABO","INSTITUTO 'I.L.V.E.M'","CORTE DEPARTAMENTAL ELECTORAL CBBA","ESCUELA SUPERIOR DE ADM. DE EMPRESAS","CENTRO DE ESTUDIOS TÉCNICOS OBISPO ANAYA","THERATOS S.R.L.","ACADEMIA COMERCIAL '14 DE SEPTIEMBRE'","FEDERACIÓN NAL. COOP. AHORRO Y CRÉDITO",
								"CENTRO ITNAL. INTERC. 'EUGEN VON BOECK V'","INSTITUTO DE COMPUTACIÓN MADRE  MA OLIVA","INSTITUTO DE TAQUIG. Y MECANOG. 'GREGG'","CENEDI - ECEM","CÁMARA JUNIOR UNIÓN","CENTRO PEDAG. Y CULT. PORTALES","'CEICOM' CENTRO INFORMÁTICA Y COMPUTACIÓ","ESCUELA NACIONAL DE MAESTROS DE SUCRE","OBM Y CIA S.A.","UNIVERSIDAD NUR","ING - DATA - COMP",
								"ETHICAL HACKING","INST. TÉCNICO ELECTRÓNICO 'WESTINGHOUSE'","UNIVERSIDAD SALESIANA DE BOLIVIA","UMSS - HUV","SEMINARIO MAYOR DE SAN LUIS","ISFHLE","SEMINARIO TEOLÓGICO BAUTISTA","UNIVERSIDAD CENTRAL","UNIVERSIDAD TÉCNICA PRIVADA COSMOS UNITE","IDEPRO - FONDO FIN. PRIV. FASSIL","S.A.I.T.E.L.S.","COLEGIO DEPARTAMENTAL DE AUDITORES","INFOCAL",
								"FACULTAD DE ENFERMERÍA ELIZABETH SETON","INSTITUTO SUPERIOR  ESTUDIOS TEOLÓGICOS","UNIVERSIDAD SIMON I PATINO USIP","CASA DE LA CULTURA - USIS","UNAL","ASOC. DE SEMINARIOS E INSTIT. TEOLOGICAS","INSTITUTO CATEC","INSTITUTO FEDERICO ALVAREZ PLATA","INSTITUTO TÉCNICO UNIVERSAL","COLEGIO MARYKNOLL","INSTITUTO COLOMBIERE","CENTRO BOLIVIANO AMERICANO",
								"INSTITUTO JAIME CARRANZA SILES","CENTRO COMPUTACIONAL DEL VALLE","CEC","ICEPAL - ICEP","INTERNATIONAL CONSULTING CORPORATION","ALIANZA FRANCESA","ESCUELA SUPERIOR DE CIENCIA Y ARTE","CIBO SYSTEMS","IBTD","NORMAL CATOLICA UNIDAD  COCHABAMBA","UCB UNIDAD COCHABAMBA","UNIVERSIDAD DEL VALLE - UNIVALLE","UNIVERSIDAD MAYOR DE SAN SIMON","UNIVERSIDAD TECNICA DE ORURO - UTO",
								"SEMINARIO JUAN XXIII","UNIVERSIDAD AUTONOMA TOMAS FRIAS","ESCUELA MILITAR DE INGENIERIA EMI SC","COMUNIDAD TERAPEÚTICA PUNTITI","UNIVERSIDAD TECNOLOGICA PRIVADA STA CRUZ","CENTRO SAL Y LUZ","SEMINARIO SANTA CRUZ","UNIVERSIDAD PRIVADA DE SANTA CRUZ - UPSA","UNIVERSIDAD AUTONOMA GABRIEL RENE MORENO","ESAM ESCUELA SUPERIOR DE ADM MKT Y NEG",
								"UCB UNIDAD TARIJA","SAN BERNARDO","UNIVERSIDAD AUTONOMA DEL BENI 'JOSE BALLIVIAN'","UNIVERSIDAD TECNICA DEL BENI","FED. REG. DE TRABAJADORES  EDUC. URBANA","UNIV. DE AQUINO BOLIVIA - UDABOL ORURO","INSTITUTO COMERCIAL OBLATO","ACADEMIA DE ENSEÑANZA PROF. 'MERCANTIL'","UNIVERSIDAD DE AQUINO","INSTITUTO NORMAL SUPERIOR DOCTOR MANUEL ASCENCIO VILLARROEL","UCB SANTA CRUZ",
								"INSTITUTO NORMAL SUPERIOR ADVENTISTA","MUSEO DE HISTORIA NATURAL ALCIDE d`ORBIGNY","SERVICIO NACIONAL DE ÁREAS PROTEGIDAS (SERNAP)","INSTITUTO BOLIVIANO DE BIOLOGÍA DE ALTURA","CORPORACIÓN DE DESARROLLO DE COCHABAMBA (CORDECO)","SOCIEDAD BOLIVIANA DE BIOQUÍMICA CLÍNICA FILIAL","MINISTERIO DE PREVISIÓN SOCIAL Y SALUD PÚBLICA","ASOCIACIÓN BOLIVIANA DE INGENIERÍA SANITARIA",
								"SOCIEDAD BOLIVIANA DE CIENCIAS","CENTRO DE DOCUMENTACIÓN E INFORMACIÓN BOLIVIA (CEDIB)","FUNDACIÓN BOLIVIANA PARA LA CAPACITACIÓN DEMOCRÁTICA Y LA INVESTIGACIÓN","VIRTUAL EDUCA FUNDACIÓN IDEA","SECRETARÍA DEPARTAMENTAL DE LOS DERECHOS DE LA MADRE TIERRA (SDDMT)","SOCIEDAD DE GESTIÓN AMBIENTAL BOLIVIANA (SGAB)","GOBIERNO AUTÓNOMO DEPARTAMENTAL DE COCHABAMBA (GADC)",
								"UNIVERSIDAD PRIVADA SIMON I. PATIÑO","CATEC","INTER CONGREGACIONAL","IGLESIA METODISTA","ISEAT","DERECHO PRIVADO, FAMILIA Y PROPIEDAD INT","INST. NACIONAL SUPERIOR CATOLICO","CLASS","INALTEC","FUNDACION DE WAAL","FEDJUVE-IFFI","INSTITUTO MARYKNOLL","INST. BOLIVIANO DE NORMALIZACION-IBNORCA","COLEGIO DE ABOGADOS","FAUTAPO-CEUB","MINISTERIO DE HACIENDA","SIB","CRUZ ROJA BOLIVIANA",
								"BANCO CENTRAL DE BOLIVIA","BANCO LOS ANDES PROCREDIT","ESCUELA DE ALTOS ESTUDIOS NACIONALES","ESCUELA DE TEATRO HECHO A MANO","COLUMBUS - IBS","ISET","ESAE","UNIV. PRIVADA ABIERTA LATINOAMERICANA","ESCUELA EUROPEA DE NEGOCIOS","INSTITUTO LUIS EXPIRAL (UCB)","UABJB","ASC II","ONUDI","CADEXCO","CPROBOL","INSTITUTO VANGUARDIA","COLEGIO DE AUDITORES","GRACO","DORIGO FILMS","INSTITUTO DE INV. Y DESARROLLO MUNICIPAL",
								"UNITEPC","UNIVERSIDAD NACIONAL SIGLO XX","ECEM","UDABOL","CEMLA ","ASOCIACION DE BANCOS PRIVADOS DE BOLIVIA","CAMARA DE COMERCIO Y SERVICIOS","FUNDES","TECNOLOGICO BOLIVIANO ALEMAN","CENTRO EMPRESARIAL DE CAPACITACION","UNIVERSIDAD LATINOAMERICANA - ULAT","S.A.R.","UCATEC","UPAL","CENTRO SIMON I. PATIÑO","TUDELA & TH CONSULTING GROUP S.R.L.","COLEGIO ALEMAN SANTA MARIA","UNIDAD EDUCATIVA NUESTRA SRA. DE LA PAZ ",
								"UNIVERSIDAD AMAZONICA DE PANDO","UNIVERSIDAD JUAN MISAEL SARACHO","COLEGIO TÉCNICO AGROPECUARIO 'MARTIN CÁRDENAS'","CONSEJO DE LA JUDICIATURA","ESC. NORMAL M. SUCRE"]
Title.create([{name:"Abogado"},{name:"Administracion"},{name:"Agronomia"},{name:"Arquitecto"},{name:"Artesano"},{name:"Auditor"},{name:"Auxiliar"},{name:"Ayudante de Gerencia"},{name:"Bachiller"},{name:"Bibliotecologo"},{name:"Biologo"},{name:"Bioquimico"}])
CiuCode.create(ciu:"01111",description:"Cultivo De Cereales Y Otros Cultivos N.C.P.",group:"A")
CiuCode.create(ciu:"01112",description:	"Cultivo De Semillas Oleaginosas O Soya",group:"A")

abogado_id=Title.where(name:"Administracion").first.id
# Degree.create(name: "Escolar",title_id:abogado_id},{name: "Internacional",title_id:abogado_id},{name: "Publica",title_id:abogado_id},{name: "Direccion de Empresas",title_id:abogado_id},{name: "De Empresas",title_id:abogado_id})
auxiliar_id=Title.where(name:"Auxiliar").first.id
# Degree.crearte({name:"Contabilidad",title_id:auxiliar_id},{name:"de Oficina",title_id:auxiliar_id})
